import type { NextPage } from 'next';
import Head from 'next/head';
import { Navigation, HeroSection, About } from '../components/index';
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="dark">
        <Navigation />
        <HeroSection />
      </header>
      <About />
    </>
  );
};

export default Home;
